[rpc_endpoints]
goerli = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "build/"}]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config